#!/bin/sh

# this needs to be run once to set the secret key for the JWT

PURPLE='\033[0;35m'
RESET='\033[0m'

echo ""
echo " --- ${PURPLE}Setting JWT SECRET${RESET} ---"
echo ""
psql -Eq $DB_URI -c "ALTER DATABASE idp_raids_api SET \"app.jwt_secret\" TO \"${JWT_SECRET}\"";
