#!/bin/sh

# this needs to be run once to set the secret key for the jwt
# this is in its own file because it only needs to run once
# however, it CAN be run more than once it'll just throw an error

PURPLE='\033[0;35m'
RESET='\033[0m'
export PGPASSWORD=$DB_PASSWORD

echo ""
echo " --- ${PURPLE}Create Schemas: basic_auth & api${RESET} ---"
psql -H $DB_HOST -d $DB_NAME -U $DB_USER -c "CREATE schema IF NOT EXISTS api;";
psql -H $DB_HOST -d $DB_NAME -U $DB_USER -c "CREATE schema IF NOT EXISTS basic_auth;";

echo ""
echo " --- ${PURPLE}Adding Type: jwt_token${RESET} ---"
echo ""

psql -H $DB_HOST -d $DB_NAME -U $DB_USER -c "CREATE type basic_auth.jwt_token AS (token text);";

echo ""
echo " --- ${PURPLE}Setting DB Variable: jwt_secret${RESET} ---"
echo ""

psql -H $DB_HOST -d $DB_NAME -U $DB_USER -c "ALTER DATABASE $DB_NAME SET \"$DB_NAME.jwt_secret\" TO \"${JWT_SECRET}\";";

echo ""
echo " --- ${PURPLE}Setting DB Variable: jwt_ttl${RESET} ---"
psql -H $DB_HOST -d $DB_NAME -U $DB_USER -c "ALTER DATABASE $DB_NAME SET \"$DB_NAME.jwt_ttl\" TO \"${JWT_TTL}\";";
