#!/bin/sh

# runs all of the *.sql file in the migrations directory
# expects to be run from the root of the project directory

PURPLE='\033[0;35m'
GREEN='\033[0;32m'
RED='\033[0;31m'
RESET='\033[0m'

echo ""
echo " ------ ${RED}Running Migrations${RESET} ------"
for f in migrations/*.sql;
  do
     echo "";
     echo " ‣ ${PURPLE}$f${RESET}";
     echo "";

     # execute command with minimal logging
     # -E no echo
     # -q quietly

     # we could pipe to sed to print with indentation: | sed 's/^/ /'
     psql -Eq $DB_URI -f $f;

     # TODO: use `$?` to determine the color of the output
     if [ $? != 0 ]; then
         echo " ${RED} *** Migration Failed *** ${RESET}";
         echo " 𝘅 ${RED}$f${RESET}";
         exit $?;
     else
         echo "";
         echo " ✔ ${GREEN}$f${RESET}";
         echo "";
         echo " ---------------------------------------- ";
     fi
done
